# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jigsaw/workspace/cpp/games/sfml_game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jigsaw/workspace/cpp/games/sfml_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jigsaw/workspace/cpp/games/sfml_game/CMakeFiles /home/jigsaw/workspace/cpp/games/sfml_game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jigsaw/workspace/cpp/games/sfml_game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/build
.PHONY : engine/fast

_src/animationcomponent.o: _src/animationcomponent.cpp.o

.PHONY : _src/animationcomponent.o

# target to build an object file
_src/animationcomponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/animationcomponent.cpp.o
.PHONY : _src/animationcomponent.cpp.o

_src/animationcomponent.i: _src/animationcomponent.cpp.i

.PHONY : _src/animationcomponent.i

# target to preprocess a source file
_src/animationcomponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/animationcomponent.cpp.i
.PHONY : _src/animationcomponent.cpp.i

_src/animationcomponent.s: _src/animationcomponent.cpp.s

.PHONY : _src/animationcomponent.s

# target to generate assembly for a file
_src/animationcomponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/animationcomponent.cpp.s
.PHONY : _src/animationcomponent.cpp.s

_src/button.o: _src/button.cpp.o

.PHONY : _src/button.o

# target to build an object file
_src/button.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/button.cpp.o
.PHONY : _src/button.cpp.o

_src/button.i: _src/button.cpp.i

.PHONY : _src/button.i

# target to preprocess a source file
_src/button.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/button.cpp.i
.PHONY : _src/button.cpp.i

_src/button.s: _src/button.cpp.s

.PHONY : _src/button.s

# target to generate assembly for a file
_src/button.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/button.cpp.s
.PHONY : _src/button.cpp.s

_src/editorstate.o: _src/editorstate.cpp.o

.PHONY : _src/editorstate.o

# target to build an object file
_src/editorstate.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/editorstate.cpp.o
.PHONY : _src/editorstate.cpp.o

_src/editorstate.i: _src/editorstate.cpp.i

.PHONY : _src/editorstate.i

# target to preprocess a source file
_src/editorstate.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/editorstate.cpp.i
.PHONY : _src/editorstate.cpp.i

_src/editorstate.s: _src/editorstate.cpp.s

.PHONY : _src/editorstate.s

# target to generate assembly for a file
_src/editorstate.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/editorstate.cpp.s
.PHONY : _src/editorstate.cpp.s

_src/entity.o: _src/entity.cpp.o

.PHONY : _src/entity.o

# target to build an object file
_src/entity.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/entity.cpp.o
.PHONY : _src/entity.cpp.o

_src/entity.i: _src/entity.cpp.i

.PHONY : _src/entity.i

# target to preprocess a source file
_src/entity.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/entity.cpp.i
.PHONY : _src/entity.cpp.i

_src/entity.s: _src/entity.cpp.s

.PHONY : _src/entity.s

# target to generate assembly for a file
_src/entity.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/entity.cpp.s
.PHONY : _src/entity.cpp.s

_src/game.o: _src/game.cpp.o

.PHONY : _src/game.o

# target to build an object file
_src/game.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/game.cpp.o
.PHONY : _src/game.cpp.o

_src/game.i: _src/game.cpp.i

.PHONY : _src/game.i

# target to preprocess a source file
_src/game.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/game.cpp.i
.PHONY : _src/game.cpp.i

_src/game.s: _src/game.cpp.s

.PHONY : _src/game.s

# target to generate assembly for a file
_src/game.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/game.cpp.s
.PHONY : _src/game.cpp.s

_src/gamestate.o: _src/gamestate.cpp.o

.PHONY : _src/gamestate.o

# target to build an object file
_src/gamestate.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/gamestate.cpp.o
.PHONY : _src/gamestate.cpp.o

_src/gamestate.i: _src/gamestate.cpp.i

.PHONY : _src/gamestate.i

# target to preprocess a source file
_src/gamestate.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/gamestate.cpp.i
.PHONY : _src/gamestate.cpp.i

_src/gamestate.s: _src/gamestate.cpp.s

.PHONY : _src/gamestate.s

# target to generate assembly for a file
_src/gamestate.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/gamestate.cpp.s
.PHONY : _src/gamestate.cpp.s

_src/hitboxcomponent.o: _src/hitboxcomponent.cpp.o

.PHONY : _src/hitboxcomponent.o

# target to build an object file
_src/hitboxcomponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/hitboxcomponent.cpp.o
.PHONY : _src/hitboxcomponent.cpp.o

_src/hitboxcomponent.i: _src/hitboxcomponent.cpp.i

.PHONY : _src/hitboxcomponent.i

# target to preprocess a source file
_src/hitboxcomponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/hitboxcomponent.cpp.i
.PHONY : _src/hitboxcomponent.cpp.i

_src/hitboxcomponent.s: _src/hitboxcomponent.cpp.s

.PHONY : _src/hitboxcomponent.s

# target to generate assembly for a file
_src/hitboxcomponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/hitboxcomponent.cpp.s
.PHONY : _src/hitboxcomponent.cpp.s

_src/main.o: _src/main.cpp.o

.PHONY : _src/main.o

# target to build an object file
_src/main.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/main.cpp.o
.PHONY : _src/main.cpp.o

_src/main.i: _src/main.cpp.i

.PHONY : _src/main.i

# target to preprocess a source file
_src/main.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/main.cpp.i
.PHONY : _src/main.cpp.i

_src/main.s: _src/main.cpp.s

.PHONY : _src/main.s

# target to generate assembly for a file
_src/main.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/main.cpp.s
.PHONY : _src/main.cpp.s

_src/mainmenustate.o: _src/mainmenustate.cpp.o

.PHONY : _src/mainmenustate.o

# target to build an object file
_src/mainmenustate.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/mainmenustate.cpp.o
.PHONY : _src/mainmenustate.cpp.o

_src/mainmenustate.i: _src/mainmenustate.cpp.i

.PHONY : _src/mainmenustate.i

# target to preprocess a source file
_src/mainmenustate.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/mainmenustate.cpp.i
.PHONY : _src/mainmenustate.cpp.i

_src/mainmenustate.s: _src/mainmenustate.cpp.s

.PHONY : _src/mainmenustate.s

# target to generate assembly for a file
_src/mainmenustate.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/mainmenustate.cpp.s
.PHONY : _src/mainmenustate.cpp.s

_src/movementcomponent.o: _src/movementcomponent.cpp.o

.PHONY : _src/movementcomponent.o

# target to build an object file
_src/movementcomponent.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/movementcomponent.cpp.o
.PHONY : _src/movementcomponent.cpp.o

_src/movementcomponent.i: _src/movementcomponent.cpp.i

.PHONY : _src/movementcomponent.i

# target to preprocess a source file
_src/movementcomponent.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/movementcomponent.cpp.i
.PHONY : _src/movementcomponent.cpp.i

_src/movementcomponent.s: _src/movementcomponent.cpp.s

.PHONY : _src/movementcomponent.s

# target to generate assembly for a file
_src/movementcomponent.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/movementcomponent.cpp.s
.PHONY : _src/movementcomponent.cpp.s

_src/pausemenu.o: _src/pausemenu.cpp.o

.PHONY : _src/pausemenu.o

# target to build an object file
_src/pausemenu.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/pausemenu.cpp.o
.PHONY : _src/pausemenu.cpp.o

_src/pausemenu.i: _src/pausemenu.cpp.i

.PHONY : _src/pausemenu.i

# target to preprocess a source file
_src/pausemenu.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/pausemenu.cpp.i
.PHONY : _src/pausemenu.cpp.i

_src/pausemenu.s: _src/pausemenu.cpp.s

.PHONY : _src/pausemenu.s

# target to generate assembly for a file
_src/pausemenu.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/pausemenu.cpp.s
.PHONY : _src/pausemenu.cpp.s

_src/player.o: _src/player.cpp.o

.PHONY : _src/player.o

# target to build an object file
_src/player.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/player.cpp.o
.PHONY : _src/player.cpp.o

_src/player.i: _src/player.cpp.i

.PHONY : _src/player.i

# target to preprocess a source file
_src/player.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/player.cpp.i
.PHONY : _src/player.cpp.i

_src/player.s: _src/player.cpp.s

.PHONY : _src/player.s

# target to generate assembly for a file
_src/player.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/player.cpp.s
.PHONY : _src/player.cpp.s

_src/settingsstate.o: _src/settingsstate.cpp.o

.PHONY : _src/settingsstate.o

# target to build an object file
_src/settingsstate.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/settingsstate.cpp.o
.PHONY : _src/settingsstate.cpp.o

_src/settingsstate.i: _src/settingsstate.cpp.i

.PHONY : _src/settingsstate.i

# target to preprocess a source file
_src/settingsstate.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/settingsstate.cpp.i
.PHONY : _src/settingsstate.cpp.i

_src/settingsstate.s: _src/settingsstate.cpp.s

.PHONY : _src/settingsstate.s

# target to generate assembly for a file
_src/settingsstate.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/settingsstate.cpp.s
.PHONY : _src/settingsstate.cpp.s

_src/state.o: _src/state.cpp.o

.PHONY : _src/state.o

# target to build an object file
_src/state.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/state.cpp.o
.PHONY : _src/state.cpp.o

_src/state.i: _src/state.cpp.i

.PHONY : _src/state.i

# target to preprocess a source file
_src/state.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/state.cpp.i
.PHONY : _src/state.cpp.i

_src/state.s: _src/state.cpp.s

.PHONY : _src/state.s

# target to generate assembly for a file
_src/state.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/state.cpp.s
.PHONY : _src/state.cpp.s

_src/tile.o: _src/tile.cpp.o

.PHONY : _src/tile.o

# target to build an object file
_src/tile.cpp.o:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/tile.cpp.o
.PHONY : _src/tile.cpp.o

_src/tile.i: _src/tile.cpp.i

.PHONY : _src/tile.i

# target to preprocess a source file
_src/tile.cpp.i:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/tile.cpp.i
.PHONY : _src/tile.cpp.i

_src/tile.s: _src/tile.cpp.s

.PHONY : _src/tile.s

# target to generate assembly for a file
_src/tile.cpp.s:
	$(MAKE) -f CMakeFiles/engine.dir/build.make CMakeFiles/engine.dir/_src/tile.cpp.s
.PHONY : _src/tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... edit_cache"
	@echo "... _src/animationcomponent.o"
	@echo "... _src/animationcomponent.i"
	@echo "... _src/animationcomponent.s"
	@echo "... _src/button.o"
	@echo "... _src/button.i"
	@echo "... _src/button.s"
	@echo "... _src/editorstate.o"
	@echo "... _src/editorstate.i"
	@echo "... _src/editorstate.s"
	@echo "... _src/entity.o"
	@echo "... _src/entity.i"
	@echo "... _src/entity.s"
	@echo "... _src/game.o"
	@echo "... _src/game.i"
	@echo "... _src/game.s"
	@echo "... _src/gamestate.o"
	@echo "... _src/gamestate.i"
	@echo "... _src/gamestate.s"
	@echo "... _src/hitboxcomponent.o"
	@echo "... _src/hitboxcomponent.i"
	@echo "... _src/hitboxcomponent.s"
	@echo "... _src/main.o"
	@echo "... _src/main.i"
	@echo "... _src/main.s"
	@echo "... _src/mainmenustate.o"
	@echo "... _src/mainmenustate.i"
	@echo "... _src/mainmenustate.s"
	@echo "... _src/movementcomponent.o"
	@echo "... _src/movementcomponent.i"
	@echo "... _src/movementcomponent.s"
	@echo "... _src/pausemenu.o"
	@echo "... _src/pausemenu.i"
	@echo "... _src/pausemenu.s"
	@echo "... _src/player.o"
	@echo "... _src/player.i"
	@echo "... _src/player.s"
	@echo "... _src/settingsstate.o"
	@echo "... _src/settingsstate.i"
	@echo "... _src/settingsstate.s"
	@echo "... _src/state.o"
	@echo "... _src/state.i"
	@echo "... _src/state.s"
	@echo "... _src/tile.o"
	@echo "... _src/tile.i"
	@echo "... _src/tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

